server:
  port: 8004

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
    lease-renewal-interval-in-seconds: 30 #向注册中心中注册服务id
    lease-expiration-duration-in-seconds: 90 #续约到期时间，如果90秒内没有向注册中心注册服务，表示这个服务宕机了，注册中心会将这个服务剔除
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/



spring:
  application:
    name: provider-ticket
