server:
  port: 9102

spring:
  application:
    name: CONSUMER-USER

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址 学习：https://study.163.com/course/courseMain.htm?courseId=1209401930
  client:
    register-with-eureka: false #不把自己注册到eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


#这个好像被优化了，如果提供服务端，有一个服务宕机了，会自动重试，不会的话就配置下面这些
#consumer-user:
#  ribbon:
#    ConnectTimeout: 250 #Ribbon的连接超时时间
#    ReadTimeOut: 1000 #Ribbon的数据读取超时时间
#    OkToRetryOnAllOperations: true #是否对所有操作都进行重试
#    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
#    MaxAutoRetries: 1 #对当前实例的重试次数


logging:
  level:
    com.ljtao3.consumeruser.feign.DbbaseProductFeignClient: DEBUG
